name: Spring Boot CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Running Verify Lifecycle
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Verify code executing each default lifecycle phase and IT tests
      run: mvn -B clean verify
      working-directory: ./air-quality-service
  sonarQube:
    runs-on: ubuntu-latest
    name: SonarQube Code Analysis
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Send code to SonarQube server and wait for quality gate
      run: mvn -B clean verify sonar:sonar -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} #-Dsonar.qualitygate.wait=true
      working-directory: ./air-quality-service
